### ISSUE TITLE
Add CI for master branch

### ISSUE THREAD

**Issue by kevin-delmas** [onera/pml-analyzer#8]
Use Github workflow to compile and run integration tests on push.
Template are available [here](https://github.com/scala/scala3-staging.g8/blob/main/.github/workflows/ci.yml)

**Comment by kevin-delmas** [comment]
The problem is here that MONOSAT should be fetched and compiled since release with JAVA API is not avalaible.
It may be really tedious and inefficient to do that during a github action

**Comment by Gaudeval** [comment]
It might be worth assessing how to generate new versions on PR completion as well. Could be a separate ticket.

**Comment by kevin-delmas** [comment]
After many tries, we now have an operational action that triggers sbt tests on push and PR on master 😄
@FredBoniol For now the action is simply running the interference analysis for the SimpleKeystone. We should check that the generated itf are correct and store that as test resource

**Comment by kevin-delmas** [comment]
The CI is set up and now automatically requested for pull request.
Closing the issue
